platform :ios, '10.0'

target 'DBChainKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DBChainKitDemo
	pod 'DBChainKit', :path => '../'

#  pod 'DBChainKit/Sm2'
#  pod 'DBChainKit/secp256k1'
  
end
